#!/bin/bash

function prompt_user()
{
    if [ $(id -u) != 0 ]; then
        echo -n "$yellow$(whoami)@"
    fi
}

function prompt_hostname()
{
    if [ `hostname` == 'limbo' ]; then
        hostname_color=$magenta
    else
        hostname_color=$green
    fi
    echo -n "${hostname_color}$(hostname)"
}

function prompt_path()
{
    echo -n "$white${PWD/#$HOME/~}"
}

function prompt_end()
{
    if [ "$1" == "0" ]; then
        echo -n $bold_green
    else
        echo -n $red
        if [ "$1" != "1" ]; then
            echo -n "!$1"
        fi
    fi
    echo -n ">$white "
}

function set_prompt()
{
    exit_code="$?"
    PS1="$(prompt_user)$(prompt_hostname) $(prompt_path)$(prompt_end $exit_code)"
}

PROMPT_COMMAND='set_prompt'
